// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Who struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Who) Reset()         { *m = Who{} }
func (m *Who) String() string { return proto.CompactTextString(m) }
func (*Who) ProtoMessage()    {}
func (*Who) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Who) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Who.Unmarshal(m, b)
}
func (m *Who) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Who.Marshal(b, m, deterministic)
}
func (m *Who) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Who.Merge(m, src)
}
func (m *Who) XXX_Size() int {
	return xxx_messageInfo_Who.Size(m)
}
func (m *Who) XXX_DiscardUnknown() {
	xxx_messageInfo_Who.DiscardUnknown(m)
}

var xxx_messageInfo_Who proto.InternalMessageInfo

func (m *Who) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloEnvoy struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloEnvoy) Reset()         { *m = HelloEnvoy{} }
func (m *HelloEnvoy) String() string { return proto.CompactTextString(m) }
func (*HelloEnvoy) ProtoMessage()    {}
func (*HelloEnvoy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *HelloEnvoy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloEnvoy.Unmarshal(m, b)
}
func (m *HelloEnvoy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloEnvoy.Marshal(b, m, deterministic)
}
func (m *HelloEnvoy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloEnvoy.Merge(m, src)
}
func (m *HelloEnvoy) XXX_Size() int {
	return xxx_messageInfo_HelloEnvoy.Size(m)
}
func (m *HelloEnvoy) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloEnvoy.DiscardUnknown(m)
}

var xxx_messageInfo_HelloEnvoy proto.InternalMessageInfo

func (m *HelloEnvoy) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Who)(nil), "proto.Who")
	proto.RegisterType((*HelloEnvoy)(nil), "proto.HelloEnvoy")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x92, 0x5c, 0xcc, 0xe1, 0x19,
	0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x60, 0xb6, 0x92, 0x1a, 0x17, 0x97, 0x47, 0x6a, 0x4e, 0x4e, 0xbe, 0x6b, 0x5e, 0x59, 0x7e, 0xa5,
	0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x11, 0x8c, 0x6b, 0x64, 0xc2,
	0xc5, 0x0a, 0x56, 0x27, 0xa4, 0xcd, 0xc5, 0x11, 0x9c, 0x58, 0x09, 0x61, 0x73, 0x41, 0xac, 0xd1,
	0x0b, 0xcf, 0xc8, 0x97, 0x12, 0x84, 0xb2, 0x11, 0xa6, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xc5, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0x61, 0xc0, 0xfa, 0x94, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	SayHello(ctx context.Context, in *Who, opts ...grpc.CallOption) (*HelloEnvoy, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *Who, opts ...grpc.CallOption) (*HelloEnvoy, error) {
	out := new(HelloEnvoy)
	err := c.cc.Invoke(ctx, "/proto.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	SayHello(context.Context, *Who) (*HelloEnvoy, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Who)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*Who))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
